---
title: LogAupair
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: franziska.klamm@googlemail.com
description: 'Speech therapist in Mamaroneck, NY

'
baseurl: ''
lang: en
url: ''
github_username: logaupair
disqus_username: logaupair-github-io
markdown: kramdown
relative_permalinks: false
permalink: "/:categories/:title/"
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"
compress_html:
  comments:
  - "<!-- "
  - " -->"
  clippings: all
  endings: all
sass:
  sass_dir: assets/_sass
images: "/assets/images"
social: 
